REPLICATION_KEYS = ["lastmodifieddate", "lastmoddate"]

RETRYABLE_ERRORS = [
    "ACCT_TEMP_UNAVAILABLE",
    "BILL_PAY_STATUS_UNAVAILABLE",
    "BILLPAY_SRVC_UNAVAILBL",
    "PAYROLL_IN_PROCESS",
]

SEARCH_ONLY_FIELDS = ["AccountingTransaction", "Item", "Transaction"]

CUSTOM_SEARCH_FIELDS = {
    "TransactionSearchBasic": [
        "AssemblyBuild",
        "AssemblyUnbuild",
        "BinTransfer",
        "BinWorksheet",
        "CashRefund",
        "CashSale",
        "Check",
        "CreditMemo",
        "CustomerDeposit",
        "CustomerPayment",
        "CustomerRefund",
        "CustomPurchase",
        "CustomSale",
        "Deposit",
        "DepositApplication",
        "Estimate",
        "ExpenseReport",
        "InterCompanyJournalEntry",
        "InventoryAdjustment",
        "InventoryCostRevaluation",
        "InventoryTransfer",
        "Invoice",
        "ItemFulfillment",
        "ItemReceipt",
        "JournalEntry",
        "Opportunity",
        "PaycheckJournal",
        "PurchaseOrder",
        "ReturnAuthorization",
        "SalesOrder",
        "StatisticalJournalEntry",
        "TransferOrder",
        "VendorBill",
        "VendorCredit",
        "VendorPayment",
        "VendorReturnAuthorization",
        "WorkOrder",
        "WorkOrderClose",
        "WorkOrderCompletion",
        "WorkOrderIssue",
    ],
    "ItemSearchBasic": ["InventoryItem"],
    "CustomerSearch": ["CustomerSearchBasic"],
}

ADVANCED_SEARCH_TYPES_AND_URNS = {
    "CalendarEventSearchAdvanced": "scheduling_2025_1.activities.webservices.netsuite.com",
    "TaskSearchAdvanced": "scheduling_2025_1.activities.webservices.netsuite.com",
    "PhoneCallSearchAdvanced": "scheduling_2025_1.activities.webservices.netsuite.com",
    "FileSearchAdvanced": "filecabinet_2025_1.documents.webservices.netsuite.com",
    "FolderSearchAdvanced": "filecabinet_2025_1.documents.webservices.netsuite.com",
    "NoteSearchAdvanced": "communication_2025_1.general.webservices.netsuite.com",
    "MessageSearchAdvanced": "communication_2025_1.general.webservices.netsuite.com",
    "ItemSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "AccountSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "BinSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "ClassificationSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "DepartmentSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "LocationSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "GiftCertificateSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "SalesTaxItemSearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "SubsidiarySearchAdvanced": "accounting_2025_1.lists.webservices.netsuite.com",
    "EmployeeSearchAdvanced": "employees_2025_1.lists.webservices.netsuite.com",
    "CampaignSearchAdvanced": "marketing_2025_1.lists.webservices.netsuite.com",
    "PromotionCodeSearchAdvanced": "marketing_2025_1.lists.webservices.netsuite.com",
    "ContactSearchAdvanced": "relationships_2025_1.lists.webservices.netsuite.com",
    "CustomerSearchAdvanced": "relationships_2025_1.lists.webservices.netsuite.com",
    "PartnerSearchAdvanced": "relationships_2025_1.lists.webservices.netsuite.com",
    "VendorSearchAdvanced": "relationships_2025_1.lists.webservices.netsuite.com",
    "EntityGroupSearchAdvanced": "relationships_2025_1.lists.webservices.netsuite.com",
    "JobSearchAdvanced": "relationships_2025_1.lists.webservices.netsuite.com",
    "SiteCategorySearchAdvanced": "website_2025_1.lists.webservices.netsuite.com",
    "SupportCaseSearchAdvanced": "support_2025_1.lists.webservices.netsuite.com",
    "SolutionSearchAdvanced": "support_2025_1.lists.webservices.netsuite.com",
    "TopicSearchAdvanced": "support_2025_1.lists.webservices.netsuite.com",
    "IssueSearchAdvanced": "support_2025_1.lists.webservices.netsuite.com",
    "CustomRecordSearchAdvanced": "customization_2025_1.setup.webservices.netsuite.com",
    "TimeBillSearchAdvanced": "employees_2025_1.lists.webservices.netsuite.com",
    "BudgetSearchAdvanced": "financial_2025_1.transactions.webservices.netsuite.com",
    "AccountingTransactionSearchAdvanced": "sales_2025_1.transactions.webservices.netsuite.com",
    "OpportunitySearchAdvanced": "sales_2025_1.transactions.webservices.netsuite.com",
    "TransactionSearchAdvanced": "sales_2025_1.transactions.webservices.netsuite.com"
}
